/* Automatically generated by configure */
#ifndef GF_CONFIG_H
#define GF_CONFIG_H
#define GPAC_CONFIGURATION "--disable-ssl"
#define GPAC_CONFIG_LINUX
#define GPAC_DISABLE_3D
#define GPAC_HAS_IPV6
#define GPAC_64_BITS
#define GPAC_HAS_LINUX_DVB
#endif
